# Generated by Django 4.1.6 on 2023-02-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='posts/%Y%m%d'),
        ),
    ]
