# Generated by Django 4.1.6 on 2023-02-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_ingredientlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredient',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
