# Generated by Django 4.1.5 on 2023-02-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='number',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
