# Generated by Django 4.1.5 on 2023-02-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_like_number_like_like_post_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='like_value',
        ),
    ]
