# Generated by Django 4.1.6 on 2023-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_like_like_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredient_quantity',
            field=models.TextField(default=''),
        ),
    ]
