# Generated by Django 4.1.5 on 2023-02-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_value',
            field=models.BooleanField(default=False),
        ),
    ]
